# Generated by Django 4.2.23 on 2026-06-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
