# Generated by Django 4.2.23 on 2026-07-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
