# Generated by Django 4.2.23 on 2026-06-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
