# Generated by Django 4.2.23 on 2026-07-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_companiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
