# Generated by Django 4.2.23 on 2026-07-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_images_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
