# Generated by Django 4.2.23 on 2026-07-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
