# Generated by Django 4.2.23 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_history_address_alter_history_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
